repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run --all-extras pytest --cov=volumeleaders --cov-report=xml --cov-report=term-missing --cov-fail-under=95
        language: system
        pass_filenames: false
        always_run: true
      - id: pyright
        name: pyright
        entry: uv run --all-extras pyright src
        language: system
        pass_filenames: false
        always_run: true
      - id: xenon
        name: xenon
        entry: uv run --all-extras xenon --max-absolute B src
        language: system
        pass_filenames: false
        always_run: true
