"""Public package exports for the VolumeLeaders client."""

from volumeleaders._client import VolumeLeadersClient
from volumeleaders.endpoints import (
    get_ah_institutional_volume,
    get_alert_configs,
    get_all_snapshots,
    get_chart_levels,
    get_company,
    get_earnings,
    get_exhaustion_scores,
    get_institutional_volume,
    get_price_data,
    get_snapshot,
    get_total_volume,
    get_trade_alerts,
    get_trade_cluster_alerts,
    get_trade_cluster_bombs,
    get_trade_clusters,
    get_trade_level_touches,
    get_trade_levels,
    get_trades,
    get_watchlist_configs,
    get_watchlist_tickers,
)
from volumeleaders.models import (
    AlertConfig,
    AspNetDate,
    Company,
    Earnings,
    ExhaustionScore,
    InstitutionalVolume,
    LastTrade,
    PriceBar,
    Quote,
    Snapshot,
    SnapshotResponse,
    TotalVolume,
    Trade,
    TradeAlert,
    TradeCluster,
    TradeClusterAlert,
    TradeClusterBomb,
    TradeLevel,
    TradeLevelTouch,
    VLBaseModel,
    WatchListConfig,
    WatchListTicker,
)

__all__ = [
    "AlertConfig",
    "AspNetDate",
    "Company",
    "Earnings",
    "ExhaustionScore",
    "InstitutionalVolume",
    "LastTrade",
    "PriceBar",
    "Quote",
    "Snapshot",
    "SnapshotResponse",
    "TotalVolume",
    "Trade",
    "TradeAlert",
    "TradeCluster",
    "TradeClusterAlert",
    "TradeClusterBomb",
    "TradeLevel",
    "TradeLevelTouch",
    "VLBaseModel",
    "VolumeLeadersClient",
    "WatchListConfig",
    "WatchListTicker",
    "get_ah_institutional_volume",
    "get_alert_configs",
    "get_all_snapshots",
    "get_chart_levels",
    "get_company",
    "get_earnings",
    "get_exhaustion_scores",
    "get_institutional_volume",
    "get_price_data",
    "get_snapshot",
    "get_total_volume",
    "get_trade_alerts",
    "get_trade_cluster_alerts",
    "get_trade_cluster_bombs",
    "get_trade_clusters",
    "get_trade_level_touches",
    "get_trade_levels",
    "get_trades",
    "get_watchlist_configs",
    "get_watchlist_tickers",
]


def main() -> None:
    """Entrypoint placeholder for local CLI invocation."""
    print("Use VolumeLeadersClient and endpoint functions from this package.")
